# Generated by Django 4.2.3 on 2023-07-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WD', 'Web development'), ('MA', 'Mobile Application'), ('DA', 'Desktop Application')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('DJ', 'Django'), ('PY', 'Python'), ('FL', 'Flask'), ('WB', 'Web2py'), ('AWS', 'AWS'), ('HT', 'HTML'), ('JS', 'JavaScript'), ('TY', 'Typescript'), ('JA', 'Java'), ('CSS', 'CSS'), ('DC', 'Docker'), ('PHP', 'PHP'), ('SQL', 'SQL'), ('SQ', 'SQLite3'), ('PG', 'PostgrelSQL'), ('MQ', 'MySQL'), ('RA', 'RESTAPI'), ('DRF', 'Django Rest Framework')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=250)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='port.category')),
                ('skill', models.ManyToManyField(to='port.skills')),
            ],
            options={
                'ordering': ['-update', '-date_added'],
            },
        ),
    ]
