# Generated by Django 4.2.3 on 2023-07-25 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_projects_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projects',
            name='update',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
