# Generated by Django 4.2.3 on 2023-07-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_remove_blogpost_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
    ]
